services:
  redis:
    image: redis:7.0
    ports:
      - "6380:6379"
    tty: true             
    stdin_open: true

  chatroom-server:
    image: chatroom-server:latest
    network_mode: host      
    tty: true               
    stdin_open: true
    depends_on:
      - redis

  fserver:
    image: chatroom-fserver:latest
    ports:
      - "9090:9090"