FROM ubuntu:25.04

# 设置非交互式环境变量（避免apt安装提示）
ENV DEBIAN_FRONTEND=noninteractive

# 安装基础工具和依赖项
RUN apt-get update && \
    apt-get install -y \
    cmake \
    curl \
    libjsoncpp-dev \
    libprotobuf-dev \
    protobuf-compiler \
    libssl-dev \  
    && rm -rf /var/lib/apt/lists/*

COPY ./depends/libcpp_redis.so.4.4.0 /usr/local/lib/libcpp_redis.so.4.4.0

RUN ldconfig

RUN mkdir /app

COPY ./build/server /app/server

CMD ["/app/server"]